services:
  smartermail:
    image: peppershade/smartermail:8930
    # Host mode is recommended
    network_mode: "host"
    # Set the timezone to your local timezone (IMPORTANT)
    environment:
      - TZ=Europe/Berlin
#    ports:
#      - 80:80
#      - 443:443
#      - 443/udp:443/udp
#      - 110:110
#      - 25:25
#      - 587:587
#      - 110:110
#      - 143:143
#      - 993:993
#      - 995:995
#      - 465:465
#      - 5222:5222
    volumes:
      - ./maildata:/var/lib/smartermail
      - ./mailconfig:/etc/smartermail