services:
  app:
    image: peppershade/smartermail:8930
    ports:
      - 80:80
      - 443:443
      - 587:587
      - 110:110
      - 143:143
      - 993:993
      - 995:995
    volumes:
      - ./maildata:/var/lib/smartermail
      - ./mailconfig:/etc/smartermail